apiVersion: v1
kind: Service
metadata:
  name: influxdb2
  labels: {{ include "common.labels" . | nindent 4 }}

spec:
  selector:
    {{ include "common.labels.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 8086
