apiVersion: v1
kind: Service
metadata:
  name: flashmq
  labels: {{ include "common.labels" . | nindent 4 }}

spec:
  selector:
    {{ include "common.labels.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    protocol: TCP
    port: 8080
  - name: mqtt
    protocol: TCP
    port: 1883
---
apiVersion: v1
kind: Service
metadata:
  name: flashmq-mqtt
  labels: {{ include "common.labels" . | nindent 4 }}

spec:
  selector:
    {{ include "common.labels.selectorLabels" . | nindent 4 }}
  externalTrafficPolicy: Cluster
  ports:
  - name: mqtt
    protocol: TCP
    port: 1883
  type: LoadBalancer
  loadBalancerIP: {{ .Values.network.loadBalancerIP }}
