apiVersion: v1
kind: Service
metadata:
  name: homij-mitm
  labels: {{ include "common.labels" . | nindent 4 }}

spec:
  selector:
    {{ include "common.labels.selectorLabels" . | nindent 4 }}
  externalTrafficPolicy: Cluster
  ports:
  - name: https
    protocol: TCP
    port: 443
  type: LoadBalancer
  loadBalancerIP: {{ .Values.network.loadBalancerIP }}
